# ============================================
# DEVELOPMENT VERSION (Debian bookworm)
# Dockerfile.Apache.DEV
# ============================================
FROM php:8.4-apache-bookworm

ARG ARG_VERSION
ARG ARG_PUSH_SHA
ARG ARG_DATE

ENV IMAGE_DATE=$ARG_DATE \
    IMAGE_VERSION=$ARG_VERSION \
    PUSH_SHA=$ARG_PUSH_SHA \
    APACHE_DOCUMENT_ROOT=/var/www/html/public

# Install dependencies (Development setup - includes dev tools)
RUN apt-get update && apt-get install -y --no-install-recommends \
    libzip-dev \
    unzip \
    wget \
    curl \
    vim \
    nano \
    jq \
    git \
    openssh-client \
    && docker-php-ext-install pdo_mysql mysqli zip \
    && docker-php-source delete \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Install Composer
RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" \
    && php composer-setup.php --quiet \
    && php -r "unlink('composer-setup.php');" \
    && mv composer.phar /usr/local/bin/composer

# Enable Apache modules
RUN a2enmod rewrite headers

# Update Apache DocumentRoot to public folder
RUN sed -ri -e 's!/var/www/html!/var/www/html/public!g' /etc/apache2/sites-available/*.conf

# Create .htaccess support
RUN sed -i '/<Directory \/var\/www\//,/<\/Directory>/ s/AllowOverride None/AllowOverride All/' /etc/apache2/apache2.conf

# Set permissions
RUN chown -R www-data:www-data /var/www/html

# Directory for backups
RUN mkdir -p /var/www/redisbackup \
    && chown -R www-data:www-data /var/www/redisbackup

# Working directory
WORKDIR /var/www/html

CMD ["apache2-foreground"]
